### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by SalamiArmy** [gmamaladze/trienet#2]
How do I turn off case sensitivity? So I can retrieve strings even when they are not the same case as the filter. As a work around I have to retrieve for each permutation of capitalization and concatenate the results together.

**Comment by gmamaladze** [comment]
Why don't you add all strings in lowercase? I mean you call .ToLower() whenever you add or search.

**Comment by SalamiArmy** [comment]
I'm just going to make do with all uppercase and all lowercase.
