### ISSUE TITLE
Not an issue - "fork" or contribution?

### ISSUE THREAD

**Issue by dgerding** [gmamaladze/trienet#6]
Hi,
I don't know if you are interested in this but I added .net core 2.1 targeted projects to your solution.  I'm new to contributing on git so please pull or let me if helpful / "what's the right way to contribute".

https://github.com/dgerding/trienet.git

I can say my limited testing does seem to support MS' claims that .net core 2.1 is faster!

Thanks again.  

Dave Gerding

**Comment by gmamaladze** [comment]
Feel free to create a pull request: https://yangsu.github.io/pull-request-tutorial/

**Comment by dgerding** [comment]
Thanks!
